---
title: "Estimador de Wavelet"
subtitle: "CE092 - Exetnsões de Modelos de Regressão
author:
- Alexandre Morales Diaz (GRR20137536)
- Bianca Salles Trentin (GRR20160214)
- Nicole Sofia Herman Marques (GRR20170387)
- Wagner Cassiano Cavalari da Silva (GRR20160208)
date: "`r Sys.Date()`"
output: beamer_presentation
---

```{r, output = F}
library(tidyr)
```

## Sinais

- Abstração de valores de uma variável onde a mesma é função de, ao menos, uma variável independente *t* (usualmente, tempo)

- Espaço
 * Contínuo: mensurável para todos os instantes de *t*
 * Discreto: mensurável apenas em intervalos específicos de *t*

## Tranformações

- Tranformação de uma função *f(t)* é uma operação matemática que resultará em uma diferente representação da mesma

- Considerando o caso de sinais, funções da variável independente *t*, temos que transformações vão... **COMPLETAR**

### Transformações de Fourrier

- Transforma um sinal *f(t)*, sendo $f(\cdot)$ função do tempo *t*, em uma função de frequência, em uma soma de funções sinusoidais.

$$F(\omega)\ =\ \int_{-\infty}^{\infty}f(t)\ e^{-i\omega\ t}d\omega$$

### Transformação de Wavelet

- Mapeia uma função *f(t)* onde *t* é a variável independente tempo, em uma função bidimencional onde *a* é referente a escala e $\tau$ é o parâmetro de deslocamento.

$$F(a,\ \tau)\ =\ \frac{1}{\sqrt{a}}\ \int_{-\infty}^{\infty}f(t)\ \psi\ (\ \frac{t\ -\ \tau}{a}\ )\ dt$$

$$F(m,\ n)\ =\ a_o^{-\frac{m}{2}}\ \int_{-\infty}^{\infty}f(t)\ \psi\ (\ a_o^{-m}\ t-n\ \tau_o\ )\ dt$$

## Estimador de Wavelet



### Teoria (Embasamento)

### Teoria (Desenvolvimento / fórmulas)

### Teoria (Aplicação)

### Aplicação

## Considerações Finais

## ReferÊncias Bibliográficos

<!-- https://x-engineer.org/signal/" -->

Wavelet Basics, 1995, Y.T.Chan
